---

- name: Variables pour chaque OS
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- include: traefik_pre_install.yml
  tags:
    - traefik-pre-install

- include: traefik_install.yml
  tags:
    - traefik-install

- include: traefik_post_install.yml
  tags:
    - traefik-post-install
