---

- name: Traefik toml file
  template: src=traefik.toml.j2 dest={{ traefik_conf_file }} mode=0644
  register: traefik_conf_state
  notify:
    - restart traefik service
    - restart traefik resource

- name: Manage non-root traefik user
  when:
    - traefik_user != 'root'
    - traefik_use_docker | lower == 'false'
  block:
    - name: Get listening ports
      set_fact:
        ports: "{{ traefik_entry_points | json_query('[].address') }}"
        set_cap: false

    - name: Loop other the listening ports
      set_fact: set_cap=true
      when: item | regex_replace('^.+?(\d+)$','\1') | int <= 1024
      with_items: "{{ ports }}"

    - name: Allow {{ traefik_user }} to bind privileged ports
      when: set_cap | lower == 'true'
      command: setcap CAP_NET_BIND_SERVICE=+eip {{ traefik_install_prefix }}/traefik

- name: Consul service definition
  when:
    - configure_consul | lower == 'true'
  template: src=service.consul.json.j2 dest={{ traefik_consul_services_path }}/{{ item.service.name }}.json
  with_items: "{{ traefik_consul }}"
  notify: reload consul

- name: (Re)start docker
  when:
    - traefik_cluster_aware | lower == 'false'
    - traefik_use_docker | lower == 'true'
  block:
    - name: Start the container
      docker_container:
        state: started
        name: "{{ traefik_container_name }}"
        image: "{{ traefik_docker_image }}"
        published_ports: "{{ traefik_docker_published_ports }}"
        volumes: "{{ traefik_docker_volumes }}"
        env: "{{ traefik_docker_env }}"
