---

- name: restart traefik service
  when:
    - traefik_post_config_restart_on_change | lower == 'true'
    - traefik_cluster_aware | lower == 'false'
    - traefik_use_docker | lower == 'false'
  service: name=traefik state=restarted enabled={{ traefik_post_install_enabled }}

- name: restart traefik resource
  when:
    - traefik_post_config_restart_on_change | lower == 'true'
    - traefik_cluster_aware | lower == 'true'
  shell: "{{ item }}"
  with_items:
    - "{{ traefik_cluster_command }} resource enable {{ traefik_cluster_resource_name }}"
    - "{{ traefik_cluster_command }} resource restart {{ traefik_cluster_resource_name }}"

- name: reload systemd
  systemd: daemon-reload=yes

- name: reload firewalld
  command: firewall-cmd --reload

- name: reload consul
  command: "{{ consul_bin }} reload"

- name: delete repo key file
  file: path="{{ repo_key_result.dest }}" state=absent
